---
- name: Remove old docker versions
  apt:
    state: absent
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc

- name: Install prerequisite packages
  apt:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python-pip
      - python-dev
      - libffi-dev
      - libssl-dev
      - gcc
      - libc-dev
      - make

- name: Import docker apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker apt repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ host_distribution_release }} stable'
    state: present
    update_cache: yes

- name: Install docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Enable docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Get docker-compose repo
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: +x

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker
